# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: cat-application
#   labels:
#     my-label: cat-application
# spec:
#   containers:
#   - name: cat-application
#     image: janesee3/cat-application:1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cat-application
spec:
  replicas: 2
  matchLabels:
    my-label: cat-application
  template:
    metadata:
      labels:
        my-label: cat-application
    spec:
        containers:
        - name: cat-application
          image: janesee3/cat-application:1
---
apiVersion: v1
kind: Service
metadata:
  name: cat-application
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: name-of-exposed-port-on-container
  selector:
    my-label: cat-application
