---
apiVersion: v1
kind: Service
metadata:
  name: cat-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: cat-application

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cat-application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cat-application
    spec:
        containers:
        - name: cat-application
          image: janesee3/cat-application:1