---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: meow-application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: meow-application
    spec:
        containers:
        - name: meow-application
          image: janesee3/meow-application:2
          env:
          - name: "DO_YOU_LIKE_CATS"
            value: "YES"
          - name: "CATS_URL"
            value: "http://cat-service:8080/cats"

---
apiVersion: v1
kind: Service
metadata:
  name: meow-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: meow-application