apiVersion: v1
kind: Service
metadata:
  name: {{ include "cat-application.fullname" . }}
  labels:
{{ include "cat-application.labels" . | indent 4 }}    
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "cat-application.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPortName }}